cache:
    paths:
    - vendor/

before_script:
- curl -sS https://getcomposer.org/installer | php
- php composer.phar install

test:5.6:
    image: php:5.6
    script:
    - vendor/bin/phpcs --standard=PSR2 -n --report=full src/OntoPress

test:5.5:
    image: php:5.6
    script:
    - vendor/bin/phpcs --standard=PSR2 -n --report=full src/OntoPress
