image: php:5.6

before_script:
- apt-get update -y -qq
- apt-get install git -y -qq > /dev/null
- curl -sS https://getcomposer.org/installer | php
- php composer.phar install -q

stages:
    - stylecheck
    - test
    - deploy

stylecheck:php:
    stage: stylecheck
    script:
    - vendor/bin/phpcs --standard=PSR2 -n --report=full src/OntoPress

stylecheck:twig:
    stage: stylecheck
    script:
    - vendor/bin/twig-lint lint src/OntoPress/Resources/views


### Waiting for php unit support
#test:5.5:
#    stage: test
#    image: php:5.5
#    script:
#    -

#test:5.6:
#    stage: test
#    image: php:5.6
#    script:
#    -
