image: php:5.6

variables:
    COMPOSER_CACHE_DIR: "/cache"

before_script:
- apt-get update -y -qq
- apt-get install git unzip php5-cli php5-curl php5-xdebug php5-sqlite -y -qq > /dev/null
- curl -sS https://getcomposer.org/installer | php
- php5 composer.phar install -q

stages:
    - stylecheck
    - test
    - deploy

stylecheck:php:
    stage: stylecheck
    script:
    - vendor/bin/phpcs --standard=PSR2 -n --report=full src/OntoPress

stylecheck:twig:
    stage: stylecheck
    script:
    - vendor/bin/twig-lint lint src/OntoPress/Resources/views


# test:5.5:
#    stage: test
#    image: php:5.5
#    script:
#    - vendor/bin/phpunit

test:5.6:
    stage: test
    image: php:5.6
    script:
    - php5 vendor/bin/phpunit --coverage-text --colors=never
