sites:
    ontopress:
        page_title: OntoPress
        menu_title: OntoPress
        capability: manage_options
        icon: dashicons-list-view
        position: 30
        controller: Dashboard:showDashboard
        sub_sites:
            ontopress:
                page_title: OntoPress Dashboard
                menu_title: Dashboard
                capability: manage_options
                controller: Dashboard:showDashboard
            ontology:
                page_title: Ontologie Verwaltung
                menu_title: Ontologien
                capability: manage_options
                controller: Ontology:showManage
            ontologyDelete:
                page_title: Löschen
                menu_title: Delete
                capability: manage_options
                controller: Ontology:showDelete
                virtual:    true
            ontologyAdd:
                page_title: Hinzufügen
                menu_title: Add
                capability: manage_options
                controller: Ontology:showAdd
                virtual:    true
            forms:
                page_title: Formular Verwaltung
                menu_title: Formulare
                capability: manage_options
                controller: Form:showManage
            formsCreate:
                page_title: Formular Anlegen
                menu_title: Formulare
                capability: manage_options
                controller: Form:showCreate
                virtual:    true
            formsEdit:
                page_title: Formular Bearbeiten
                menu_title: Formulare
                capability: manage_options
                controller: Form:showEdit
                virtual:    true
            formsDelete:
                page_title: Formular Löschen
                menu_title: Formulare
                capability: manage_options
                controller: Form:showDelete
                virtual:    true
            resource:
                page_title: Ressourcen Verwaltung
                menu_title: Ressourcen
                capability: manage_options
                controller: Resource:showManagement
            resourceAdd:
                page_title: Ressourcen
                menu_title: + Ressource
                capability: manage_options
                controller: Resource:showAdd
            resourceAddDetails:
                page_title: Ressourcen
                menu_title: + Ressource
                capability: manage_options
                controller: Resource:showAddDetails
                virtual:    true
            resourceDelete:
                page_title: Ressource Löschen
                menu_title: Ressourcen
                capability: manage_options
                controller: Resource:showDelete
                virtual:    true
            resourceEdit:
                page_title: Ressource Bearbeiten
                menu_title: Ressourcen
                capability: manage_options
                controller: Resource:showEdit
                virtual:    true
