sites:
    ontopress:
        page_title: OntoPress
        menu_title: OntoPress
        capability: manage_options
        icon: dashicons-list-view
        position: 30
        controller: Test:showTest
        sub_sites:
            ontopress:
                page_title: OntoPress Dashboard
                menu_title: Dashboard
                capability: manage_options
                controller: Test:showTest
            ontology:
                page_title: Ontologie Verwaltung
                menu_title: Ontologien
                capability: manage_options
                controller: Test:showTest
            forms:
                page_title: Formular Verwaltung
                menu_title: Formulare
                capability: manage_options
                controller: Test:showTest
            add resource:
                page_title: Ressourcen
                menu_title: + Ressource
                capability: manage_options
                controller: Test:showTest
