sites:
    ontopress:
        page_title: OntoPress
        menu_title: OntoPress
        capability: manage_options
        icon: dashicons-list-view
        position: 30
        controller: Test:showTest
        sub_sites:
            ontopress:
                page_title: PAGE_TITLE
                menu_title: MENU_TITLE
                capability: manage_options
                controller: Test:showTest
            dummy2:
                page_title: PAGE_TITLE
                menu_title: MENU_TITLE
                capability: manage_options
                controller: Test:showTest
