sites:
    ontopress:
        page_title: OntoPress
        menu_title: OntoPress
        capability: manage_options
        icon: dashicons-list-view
        position: 30
        controller: Dashboard:showDashboard
        sub_sites:
            ontopress:
                page_title: OntoPress Dashboard
                menu_title: Dashboard
                capability: manage_options
                controller: Dashboard:showDashboard
            ontology:
                page_title: Ontologie Verwaltung
                menu_title: Ontologien
                capability: manage_options
                controller: Ontology:showManage
            ontologyDelete:
                page_title: Löschen
                menu_title: Delete
                capability: manage_options
                controller: Ontology:showDelete
                virtual:    true
            forms:
                page_title: Formular Verwaltung
                menu_title: Formulare
                capability: manage_options
                controller: Form:showManage
            resource:
                page_title: Ressourcen Verwaltung
                menu_title: Ressourcen
                capability: manage_options
                controller: Resource:showManagement
            resourceAdd:
                page_title: Ressourcen
                menu_title: + Ressource
                capability: manage_options
                controller: Resource:showAdd
            resourceAddDetails:
                page_title: Ressourcen
                menu_title: + Ressource
                capability: manage_options
                controller: Resource:showAddDetails
                virtual:    true
