parameters:
    ontopress.plugin_url: /wp-content/plugins/ontologie/src/OntoPress
services:
    ontopress.ontology_parser:
        class: OntoPress\Service\OntologyParser
        arguments: [@saft.easyrdf.parser]
        lazy: true

    ontopress.sparql_manager:
        class: OntoPress\Service\SparqlManager
        arguments: [@saft.store]
        lazy: true

    ontopress.arc2_manager:
        class: OntoPress\Service\ARC2Manager
        arguments: [@saft.store, @doctrine]
        lazy: true

    ontopress.twig_generator:
        class: OntoPress\Service\TwigGenerator
        arguments: [@symfony.twig, @ontopress.restriction_helper]
        lazy: true

    ontopress.form_creation:
        class: OntoPress\Service\FormCreation
        arguments: [@symfony.form, @ontopress.restriction_helper]
        lazy: true

    ontopress.restriction_helper:
        class: OntoPress\Service\RestrictionHelper
        arguments: [@doctrine]
        lazy: true

    ontopress.router:
        class: OntoPress\Library\Router
        arguments: [@service_container]

    ontopress.twig_extension.router:
        class: OntoPress\Library\Twig\RouterExtension
        arguments: [@ontopress.router]
        public: false
        tags:
            - { name: twig.extension }

    ontopress.doctrine_manager:
        class: OntoPress\Service\DoctrineManager
        arguments: [@doctrine]

    ontopress.doctrine_schema_tool:
        class: OntoPress\Service\DoctrineSchemaTool
        arguments: [@doctrine]
