parameters:
    ontopress.plugin_url: /wp-content/plugins/ontologie/src/OntoPress
services:
    ontopress.ontology_parser:
        class:  OntoPress\Service\OntologyParser\Parser
        lazy: true

    ontopress.router:
        class: OntoPress\Library\Router
        arguments: [@service_container]

    ontopress.twig_extension.router:
        class: OntoPress\Library\Twig\RouterExtension
        arguments: [@ontopress.router]
        public: false
        tags:
            - { name: twig.extension }
